server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
spring:
  application:
    name: security-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088
          jwk-set-uri: http://localhost:8088/oauth2/jwks
  datasource:
    url: jdbc:postgresql://localhost:5432/osmSecurity
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  data:
    jdbc:
      dialect: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    username: xdevgroupe@gmail.com
    password: aqxe aofi yxzn qrvy
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
      default-encoding: UTF-8
      messages:
        cache-duration: PT1S # 1 second in ISO 8601





oauth2:
  client:
    id: osm-client
    secret: X7kP9mN2vQ8rT4wY6zA1bC3dE5fG8hJ9

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
